# Generated by Django 6.0.6 on 2026-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100, unique=True)),
                ('ward_type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('ICU', 'ICU'), ('Emergency', 'Emergency'), ('Maternity', 'Maternity')], max_length=30)),
                ('floor', models.CharField(max_length=30)),
                ('total_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('incharge', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Closed', 'Closed')], default='Available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ward_name'],
            },
        ),
    ]
